[package]
name = "run-script-rs"
version = "0.2.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
serde = { version = "1.0.210", features = [ "derive" ]}

[target."cfg(windows)".dependencies]
powershell_script = "1.1.0"

[target."cfg(unix)".dependencies]
run_script = "0.11.0"
